import javax.swing.*;

public class MenuScreen extends javax.swing.JFrame {
    /**
     * Creates new form MainLogin
     */
    public MenuScreen() {
        initComponents();
        baguetteQTY.setEnabled(false);
        croissantQTY.setEnabled(false);
        goldleafQTY.setEnabled(false);
        sourdoughQTY.setEnabled(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        closeBTN = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        baguetteRBTN = new javax.swing.JRadioButton();
        croissantRBTN = new javax.swing.JRadioButton();
        goldleafRBTN = new javax.swing.JRadioButton();
        sourdoughRBTN = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        addCart = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        baguetteQTY = new javax.swing.JSpinner();
        croissantQTY = new javax.swing.JSpinner();
        sourdoughQTY = new javax.swing.JSpinner();
        goldleafQTY = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        totalBALANCE = new javax.swing.JLabel();
        totalBalance = new javax.swing.JLabel();
        welcome = new javax.swing.JLabel();
        logOUT = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cartBTN = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        checkoutBTN = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        menuUSER = new javax.swing.JLabel();
        addBalanceSCREEN1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(49, 52, 52));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(49, 52, 52));
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.setForeground(new java.awt.Color(187, 89, 26));
        jPanel2.setLayout(null);

        closeBTN.setBackground(java.awt.Color.white);
        closeBTN.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        closeBTN.setForeground(java.awt.Color.white);
        closeBTN.setText("x");
        closeBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTNMouseClicked(evt);
            }
        });
        jPanel2.add(closeBTN);
        closeBTN.setBounds(380, 0, 30, 30);

        jPanel4.setBackground(new java.awt.Color(187, 89, 26));
        jPanel4.setForeground(new java.awt.Color(187, 89, 26));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("BREAD MENU");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jLabel7)
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(40, 30, 210, 30);

        baguetteRBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        baguetteRBTN.setForeground(java.awt.Color.white);
        baguetteRBTN.setText("Baguette");
        baguetteRBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        baguetteRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baguetteRBTNMouseClicked(evt);
            }
        });
        jPanel2.add(baguetteRBTN);
        baguetteRBTN.setBounds(40, 180, 80, 21);

        croissantRBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        croissantRBTN.setForeground(java.awt.Color.white);
        croissantRBTN.setText("Croissant");
        croissantRBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        croissantRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                croissantRBTNMouseClicked(evt);
            }
        });
        jPanel2.add(croissantRBTN);
        croissantRBTN.setBounds(220, 180, 80, 21);

        goldleafRBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        goldleafRBTN.setForeground(java.awt.Color.white);
        goldleafRBTN.setText("Gold Leaf");
        goldleafRBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        goldleafRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goldleafRBTNMouseClicked(evt);
            }
        });
        jPanel2.add(goldleafRBTN);
        goldleafRBTN.setBounds(40, 330, 80, 21);

        sourdoughRBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sourdoughRBTN.setForeground(java.awt.Color.white);
        sourdoughRBTN.setText("Sourdough");
        sourdoughRBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sourdoughRBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sourdoughRBTNMouseClicked(evt);
            }
        });
        jPanel2.add(sourdoughRBTN);
        sourdoughRBTN.setBounds(220, 330, 90, 21);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_sourdough.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(220, 230, 150, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_baguette.jpg"))); // NOI18N
        jLabel10.setText("jLabel9");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(40, 80, 150, 90);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_croissant.jpg"))); // NOI18N
        jLabel11.setText("jLabel9");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(220, 80, 150, 90);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pics/rsz_gold.jpg"))); // NOI18N
        jLabel12.setText("jLabel9");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(40, 230, 150, 90);

        addCart.setBackground(new java.awt.Color(187, 89, 26));
        addCart.setForeground(new java.awt.Color(187, 89, 26));
        addCart.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addCart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addCartMouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("ADD CART");

        javax.swing.GroupLayout addCartLayout = new javax.swing.GroupLayout(addCart);
        addCart.setLayout(addCartLayout);
        addCartLayout.setHorizontalGroup(
            addCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCartLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        addCartLayout.setVerticalGroup(
            addCartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        jPanel2.add(addCart);
        addCart.setBounds(270, 30, 100, 30);

        baguetteQTY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        baguetteQTY.setBorder(null);
        baguetteQTY.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        baguetteQTY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                baguetteQTYMouseClicked(evt);
            }
        });
        jPanel2.add(baguetteQTY);
        baguetteQTY.setBounds(140, 180, 50, 30);

        croissantQTY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        croissantQTY.setBorder(null);
        jPanel2.add(croissantQTY);
        croissantQTY.setBounds(320, 180, 50, 30);

        sourdoughQTY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        sourdoughQTY.setBorder(null);
        jPanel2.add(sourdoughQTY);
        sourdoughQTY.setBounds(320, 330, 50, 30);

        goldleafQTY.setModel(new javax.swing.SpinnerNumberModel(0, 0, 50, 1));
        goldleafQTY.setBorder(null);
        jPanel2.add(goldleafQTY);
        goldleafQTY.setBounds(140, 330, 50, 30);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("P100");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 200, 30, 16);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("P98");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(220, 200, 21, 16);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("P75");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(220, 350, 21, 16);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setText("P450");
        jPanel2.add(jLabel15);
        jLabel15.setBounds(40, 350, 28, 16);

        jPanel3.setBackground(java.awt.Color.white);

        jPanel1.setBackground(new java.awt.Color(40, 40, 61));
        jPanel1.setForeground(new java.awt.Color(40, 40, 61));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Total Balance");

        totalBALANCE.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        totalBALANCE.setForeground(java.awt.Color.white);
        totalBALANCE.setText("P");

        totalBalance.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        totalBalance.setForeground(new java.awt.Color(255, 255, 255));
        totalBalance.setText("" + AddBalancePOPUP.bal);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(totalBALANCE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(totalBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalBALANCE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(totalBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        welcome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        welcome.setForeground(java.awt.Color.black);
        welcome.setText("Welcome");

        logOUT.setBackground(new java.awt.Color(187, 89, 26));
        logOUT.setForeground(new java.awt.Color(187, 89, 26));
        logOUT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOUT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOUTMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("LOG OUT");

        javax.swing.GroupLayout logOUTLayout = new javax.swing.GroupLayout(logOUT);
        logOUT.setLayout(logOUTLayout);
        logOUTLayout.setHorizontalGroup(
            logOUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logOUTLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        logOUTLayout.setVerticalGroup(
            logOUTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        cartBTN.setBackground(new java.awt.Color(187, 89, 26));
        cartBTN.setForeground(new java.awt.Color(187, 89, 26));
        cartBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cartBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cartBTNMouseClicked(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("CART / RESET");

        javax.swing.GroupLayout cartBTNLayout = new javax.swing.GroupLayout(cartBTN);
        cartBTN.setLayout(cartBTNLayout);
        cartBTNLayout.setHorizontalGroup(
            cartBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cartBTNLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
        cartBTNLayout.setVerticalGroup(
            cartBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        checkoutBTN.setBackground(new java.awt.Color(187, 89, 26));
        checkoutBTN.setForeground(new java.awt.Color(187, 89, 26));
        checkoutBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        checkoutBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkoutBTNMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("CHECKOUT");

        javax.swing.GroupLayout checkoutBTNLayout = new javax.swing.GroupLayout(checkoutBTN);
        checkoutBTN.setLayout(checkoutBTNLayout);
        checkoutBTNLayout.setHorizontalGroup(
            checkoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkoutBTNLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel6)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        checkoutBTNLayout.setVerticalGroup(
            checkoutBTNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        menuUSER.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        menuUSER.setForeground(new java.awt.Color(40, 40, 61));
        menuUSER.setText(MainLogin.user.getText());

        addBalanceSCREEN1.setBackground(new java.awt.Color(187, 89, 26));
        addBalanceSCREEN1.setForeground(new java.awt.Color(187, 89, 26));
        addBalanceSCREEN1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBalanceSCREEN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBalanceSCREEN1MouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("ADD BALANCE");

        javax.swing.GroupLayout addBalanceSCREEN1Layout = new javax.swing.GroupLayout(addBalanceSCREEN1);
        addBalanceSCREEN1.setLayout(addBalanceSCREEN1Layout);
        addBalanceSCREEN1Layout.setHorizontalGroup(
            addBalanceSCREEN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addBalanceSCREEN1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel16)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        addBalanceSCREEN1Layout.setVerticalGroup(
            addBalanceSCREEN1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(menuUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(checkoutBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cartBTN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addBalanceSCREEN1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(logOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(28, 28, 28)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(welcome, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuUSER)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(logOUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(addBalanceSCREEN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cartBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(checkoutBTN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTNMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBTNMouseClicked

    private void checkoutBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkoutBTNMouseClicked
        CheckOutScreen check = new CheckOutScreen();
        check.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_checkoutBTNMouseClicked
    float totA = 0;
    float totB = 0;
    float totC = 0;
    float totD = 0;
    float totalAmount = 0;
    public static float totalAmount2 = 0;
    int baguette = 100;
    int croissant = 98;
    int goldLeaf = 450;
    int sourDough = 75;
    
    int qtyA = 0;
    public static int qtyA2 = 0;
    int qtyB = 0;
    public static int qtyB2 = 0;
    int qtyC = 0;
    public static int qtyC2 = 0;
    int qtyD = 0;
    public static int qtyD2 = 0;
    
    private void addCartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addCartMouseClicked
        int value = (Integer) baguetteQTY.getValue();
        int value2 = (Integer) croissantQTY.getValue();
        int value3 = (Integer) goldleafQTY.getValue();
        int value4 = (Integer) sourdoughQTY.getValue();
        
        if (value > 0 || value2 > 0 || value3 > 0 || value4 > 0){
            JOptionPane.showMessageDialog(null, "Successfully added to cart.");
        } else {
            JOptionPane.showMessageDialog(null, "Please select your bread option.");
        }
        
        qtyA = value;
        qtyA2 += qtyA;
        qtyB = value2;
        qtyB2 += qtyB;
        qtyC = value3;
        qtyC2 += qtyC;
        qtyD = value4;
        qtyD2 += qtyD;
        
        totA = baguette * value;
        totB = croissant * value2;
        totC = goldLeaf * value3;
        totD = sourDough * value4;
        totalAmount = totA + totB + totC + totD;
        totalAmount2 += totalAmount;
    }//GEN-LAST:event_addCartMouseClicked

    private void baguetteRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baguetteRBTNMouseClicked
        if (baguetteRBTN.isSelected()){
            baguetteQTY.setEnabled(true);
        } else {
            baguetteQTY.setEnabled(false);
        }
    }//GEN-LAST:event_baguetteRBTNMouseClicked

    private void goldleafRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goldleafRBTNMouseClicked
        if (goldleafRBTN.isSelected()){
            goldleafQTY.setEnabled(true);
        } else {
            goldleafQTY.setEnabled(false);
        }
    }//GEN-LAST:event_goldleafRBTNMouseClicked

    private void sourdoughRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sourdoughRBTNMouseClicked
        if (sourdoughRBTN.isSelected()){
            sourdoughQTY.setEnabled(true);
        } else {
            sourdoughQTY.setEnabled(false);
        }
    }//GEN-LAST:event_sourdoughRBTNMouseClicked

    private void croissantRBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_croissantRBTNMouseClicked
        if (croissantRBTN.isSelected()){
            croissantQTY.setEnabled(true);
        } else {
            croissantQTY.setEnabled(false);
        }
    }//GEN-LAST:event_croissantRBTNMouseClicked

    private void logOUTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOUTMouseClicked
        MainLogin main = new MainLogin();
        main.show();
        AddBalancePOPUP.bal = 0;
        totalAmount2 = 0;
        qtyA2 = 0;
        qtyB2 = 0;
        qtyC2 = 0;
        qtyD2 = 0;
        this.dispose();
    }//GEN-LAST:event_logOUTMouseClicked

    private void cartBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cartBTNMouseClicked
        CartPOPUP cart = new CartPOPUP();
        cart.show();
    }//GEN-LAST:event_cartBTNMouseClicked
  
    private void baguetteQTYMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_baguetteQTYMouseClicked

    }//GEN-LAST:event_baguetteQTYMouseClicked

    private void addBalanceSCREEN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBalanceSCREEN1MouseClicked
        AddBalancePOPUP add = new AddBalancePOPUP();
        add.setVisible(true);
    }//GEN-LAST:event_addBalanceSCREEN1MouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addBalanceSCREEN1;
    private javax.swing.JPanel addCart;
    private javax.swing.JSpinner baguetteQTY;
    private javax.swing.JRadioButton baguetteRBTN;
    private javax.swing.JPanel cartBTN;
    private javax.swing.JPanel checkoutBTN;
    private javax.swing.JLabel closeBTN;
    private javax.swing.JSpinner croissantQTY;
    private javax.swing.JRadioButton croissantRBTN;
    private javax.swing.JSpinner goldleafQTY;
    private javax.swing.JRadioButton goldleafRBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel logOUT;
    public static javax.swing.JLabel menuUSER;
    private javax.swing.JSpinner sourdoughQTY;
    private javax.swing.JRadioButton sourdoughRBTN;
    private javax.swing.JLabel totalBALANCE;
    public static javax.swing.JLabel totalBalance;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables

    
    
}
